/**
 * SKIDATA Face Recognition Box Interface Description
 * SKIDATA Face Recognition Box provides this API for web clients.
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeyValue } from './keyValue';


export interface KeyValues extends Array<KeyValue> { 
}
