swagger: "2.0"
info:
  title: "SKIDATA Face Recognition Box Interface Description"
  description: >-
    SKIDATA Face Recognition Box provides this API for web clients.
  version: 1.0.0
host: "localhost:8080"
basePath: "/"
schemes:
  - http
  - https
produces:
  - "application/json"
paths:
  /version:
    get:
      summary: "returns the version of the Face Recognition Box implementing this API"
      tags:
        - "server"
      operationId: "getVersion"
      produces:
        - "application/text"
      responses:
        200:
          description: "version information"
          schema:
            type: "string"
        401:
          description: "Unauthorized"
        500:
          description: "Error"
  /statistics:
    get:
      summary: "returns a key/value map describing relevant statistics"
      tags:
        - "server"
      operationId: "getStatistics"
      responses:
        200:
          description: "key/value list"
          schema:
            $ref: '#/definitions/KeyValues'
        401:
          description: "Unauthorized"
        500:
          description: "Error"

  /enroll:
    post:
      tags:
        - "enrollment"
      summary: "enrolls an identification with an image of the persons face"
      description: "If there is a enrolled identification the image is added to the set of images to be used as references.
      To remove a single reference image, use DELETE /enroll and then POST /enroll."
      operationId: "updateEnrollment"
      consumes:
        - "multipart/form-data"
      parameters:
        - in: formData
          name: "name"
          description: "name of the holder of the ticket"
          required: true
          type: "string"
        - in: formData
          name: "file"
          description: "file to upload"
          required: true
          type: "file"
      responses:
        200:
          description: "enrollment reference data"
          schema:
            $ref: '#/definitions/Enrollment'
        400:
          description: "no face found"
        401:
          description: "Unauthorized"
        500:
          description: "Error"
  /enroll/{name}:
    get:
      tags:
        - "enrollment"
      summary: "get the information of an enrollment"
      operationId: "getEnrollment"
      parameters:
        - in: path
          name: "name"
          type: "string"
          required: true
          description: "name (of persone) for which enrollment was done"
      responses:
        200:
          description: "enrollment reference data"
          schema:
            $ref: '#/definitions/Enrollment'
        401:
          description: "Unauthorized"
        404:
          description: "no enrollment found"
        500:
          description: "Error"
    delete:
      tags:
        - "enrollment"
      summary: "delete the enrollment for the ticket id"
      operationId: deleteEnrollment
      parameters:
        - in: path
          name: "name"
          type: "string"
          required: true
          description: "name (of person) to delete enrollment for"
      responses:
        200:
          description: "OK, deleted (or not found)"
        401:
          description: "Unauthorized"
        500:
          description: "Error"

  /enroll/{name}/{image_nr}:
    get:
      tags:
        - "enrollment"
      summary: "get an image enrolled for the name, enumeration starts w/ 0"
      produces:
        - image/png
        - image/gif
        - image/jpeg
        - application/octet-stream
      operationId: "getEnrollmentImage"
      parameters:
        - in: path
          name: "name"
          type: "string"
          required: true
          description: "name(of person) for which enrollment was done"
        - in: path
          name: "image_nr"
          type: "integer"
          required: true
          description: "image number to get"
      responses:
        200:
          description: "OK"
          schema:
            type: "string"
            format: "byte"
        401:
          description: "Unauthorized"
        404:
          description: "no image with sequence image_nr found"
        500:
          description: "Error"

definitions:
  KeyValue:
    required:
      - key
    properties:
      key:
        type: "string"
      value:
        type: "string"
  KeyValues:
    type: "array"
    items:
      $ref: '#/definitions/KeyValue'

  Enrollment:
    type: "object"
    required:
      - reference_id
      - name
    properties:
      reference_id:
        type: "string"
        description: "reference id of the enrollment in the face recognition system"
      name:
        type: "string"
        description: "name of person enrolled"
      images:
        type: "integer"
        description: "number of images associated with the person enrolled"
      key_values:
        $ref: '#/definitions/KeyValues'